import type { Metadata } from "next";
import localFont from "next/font/local"

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ReactQueryProvider } from "@/components /providers/ReactQueryProvider";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Analytics } from '@vercel/analytics/next';


const nothingYCD = localFont({
  src: "./fonts/NothingYouCouldDo-Regular.ttf",
  weight: "400",
  style: "normal",
  variable: "--font-nothing-ycd",
});

const sfPro = localFont({
  src: [
    {
      path: "./fonts/SF-Pro-Display-Regular.otf",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/SF-Pro-Display-Medium.otf",
      weight: "500",
      style: "normal"
    },
    {
      path: "./fonts/SF-Pro-Display-Bold.otf",
      weight: "700",
      style: "normal"
    },
  ],
  variable: "--font-sf-pro"
});

export const metadata: Metadata = {
  title: "YIB | YeaIBreathe",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();

  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${sfPro.variable} ${nothingYCD.variable} h-full antialiased`}
      >
        <body className="min-h-screen w-full">

          <NextIntlClientProvider messages={messages}>
            <ReactQueryProvider>
              {children}
            </ReactQueryProvider>
          </NextIntlClientProvider>
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
